import './globals.css'

import type { Metadata } from 'next'
import { DM_Sans as DMSans, Poppins } from 'next/font/google'

const dmSans = DMSans({
  subsets: ['latin'],
  variable: '--font-dm-sans',
})

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${poppins.variable} ${dmSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}
